apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/aws-ebs
      volume.kubernetes.io/selected-node: ip-10-0-182-238.ec2.internal
    creationTimestamp: "2020-08-09T14:46:04Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: quotesdb-claim
    namespace: mprabhan-quotes-dev
    resourceVersion: "113372247"
    selfLink: /api/v1/namespaces/mprabhan-quotes-dev/persistentvolumeclaims/quotesdb-claim
    uid: 0d45a4ef-da4f-11ea-8b18-02e5d704b7db
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 300Mi
    storageClassName: gp2
    volumeMode: Filesystem
    volumeName: pvc-0d45a4ef-da4f-11ea-8b18-02e5d704b7db
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
